125 Zooming at max zoom pans map
NYCPlanning/ae-cp-map pull request #129
Opened 2024-12-20 15:55 UTC by dhochbaum-dcp

Fixed issue where after fully zooming out using the mouse scroller, any more scrolls move the map to the left/down.

The

2024-12-23 21:17 UTC, TangoYankee requested changes
The issue goes away for the home page. But, I get the behavior on pages that included a "zoom to", ie) `/boroughs/1/community-districts/01/capital-projects?districtType=cd&boroughId=1&districtId=01`

2024-12-24 19:12 UTC, dhochbaum-dcp commented
> The issue goes away for the home page. But, I get the behavior on pages that included a "zoom to", ie) `/boroughs/1/community-districts/01/capital-projects?districtType=cd&boroughId=1&districtId=01`

Thanks, good catch.  I've fixed that as well.

2025-01-03 19:06 UTC, TylerMatteo approved these changes

2025-01-10 17:37 UTC, TylerMatteo approved these changes

2025-01-10 17:37 UTC, TylerMatteo approved these changes

2025-01-10 17:38 UTC, merged