62 filter projects on map by ccd
NYCPlanning/ae-cp-map pull request #66
Opened 2024-08-13 14:36 UTC by pratishta

Closes https://github.com/NYCPlanning/ae-cp-map/issues/62

Waiting for the ✅ from https://github.com/NYCPlanning/ae-cp-map/pull/65 to mitigate merge conflicts. Things to note in this PR:
- I pass an empty string to data instead of using the fallback geometry
- I also added the `hasCityCouncilDistrict` boolean to both capital project and ccd layer because I wanted to more explicitly tie the highlighting of the district and the filtered project tiles together in the code

2024-08-13 16:46 UTC, TangoYankee requested changes
This error occurs when using an empty string as the `data` value on a GeoJSONLayer. 

<img width="853" alt="Screenshot 2024-08-13 at 12 38 39 PM" src="https://github.com/user-attachments/assets/b29885d7-fb83-43da-b75b-ffe09b208b60">


I know the `fallbackGeometry` feels hacky. But unless there is a significant issue with it, we should stick with it for now. It addresses the known error without causing knock-on problems. This frees our time to focus on the features that still need to be completed by the end of this sprint.

2024-08-13 18:03 UTC, pratishta commented
@TangoYankee Okay thanks for flagging what the error was. There's no significant issue with `fallbackGeometry` but if it's possible to use an empty value for a layer data at this point in dev, I think we should.  I used `[]` instead of `""` and I didn't get that error. Is that the case for you as well? (Looking at the default value here: https://deck.gl/docs/api-reference/core/layer#data)

2024-08-13 18:28 UTC, TangoYankee commented
> @TangoYankee Okay thanks for flagging what the error was. There's no significant issue with `fallbackGeometry` but if it's possible to use an empty value for a layer data at this point in dev, I think we should. I used `[]` instead of `""` and I didn't get that error. Is that the case for you as well? (Looking at the default value here: https://deck.gl/docs/api-reference/core/layer#data)

Thank you for pointing this out. In which case, yes it does make more sense to use an empty array than the fallback geometry. I'll update #65 to use the empty array instead of the fallback geometry

2024-08-14 13:48 UTC, TangoYankee approved these changes
:rocket:

2024-08-14 13:56 UTC, merged